[package]
authors = ["Gufo Labs"]
description = "Gufo Agent"
edition = "2021"
name = "agent"
version = "0.1.0"

[dependencies]
block_io = {path = "../collectors/block_io"}
common = {path = "../common"}
cpu = {path = "../collectors/cpu"}
dns = {path = "../collectors/dns"}
fs = {path = "../collectors/fs"}
gethostname = "0.4"
log = "0.4"
memory = {path = "../collectors/memory"}
network = {path = "../collectors/network"}
rand = "0.8"
serde = {version = "1.0", features = ["derive"]}
serde_yaml = "0.9"
tokio = {version = "1.27", features = ["full"]}
uptime = {path = "../collectors/uptime"}
warp = "0.3"
